### ISSUE TITLE
Unable to post comments

### ISSUE THREAD

**Issue by dsonyy** [rayferric/rayferric.xyz#2]
After login with GitHub, unable to post comment here: https://rayferric.xyz/posts/dithering-&-shaders

After submitting, no comment appears, and an error box showed: 
![image](https://github.com/rayferric/rayferric.xyz/assets/25373558/bd769ea6-9e6f-4b1a-abb7-98e8c1c5bba6)

**Comment by rayferric** [comment]
Thank you for your report. The issue was that I did not re-install Utterances in this repository after it was renamed from `rayferric.github.io`. Now that I've done the re-install, comments should be up and running smoothly.
